### ISSUE TITLE
Implement Projects in the front end

### ISSUE THREAD

**Issue by gotsanity** [CCAppDevs/ModelCabinet#23]
For this to be completed the following tasks need to be completed:

- [x] Implement a Project model in TypeScript (See #16)
- [x] Implement a Project Item Component (to display a single project)
    - [x] The Project Item Component needs to take in a Project model as an input.
- [x] Implement a Project List Component (to display multiple Project Item Components)
    - [x] The Project List Component needs to take in an array of project models as an input.

**Comment by GiftedR** [comment]
#42

**Comment by gotsanity** [comment]
Merged
